# Hand-transcribed from lows/P1|P2|P3/WRITERS.json (outcome fixed) + lows/remaining/REMAINING.json (fixed_untested).
# (entry, kind, file, name)  kind: py | vt (vitest; name None = whole file, "D:" prefix = describe block, "P:" = title prefix) | rs (cargo, chain log)
T = "sidecar/tests/"
S = [
 ("R15-AGENT-079","py",T+"test_backtest_lows.py","test_uppercase_and_or_parse_like_lowercase"),
 ("R15-CODE-PLATFORM-036","py",T+"test_backtest_lows.py","test_each_rule_compiled_once"),
 ("R15-CODE-PLATFORM-034","py",T+"test_backtest_lows.py","test_each_bar_in_exactly_one_slice"),
 ("R15-CODE-PLATFORM-035","py",T+"test_backtest_lows.py","test_no_dead_backtest_scaffolding"),
 ("R15-UI-060","py",T+"test_backtest_engine.py","test_event_sequence_has_progress_between_start_and_complete"),
 ("R15-UI-061","vt","src/modules/backtest/BacktestResultView.test.tsx",None),
 ("R15-AGENT-070","py",T+"test_agent_runtime.py","test_timeout_from_args_flag_not_name_selects_guard"),
 ("R15-AGENT-071","py",T+"test_agent_runtime.py","test_every_tool_named_in_prompts_resolves_in_catalog"),
 ("R15-AGENT-073","py",T+"test_agent_runtime.py","test_provider_override_without_model_uses_provider_default"),
 ("R15-AGENT-089","py",T+"test_planner.py","test_coerce_steps_keeps_close_and_focus_panel_and_plan_marks_staged"),
 ("R15-CODE-AGENT-018","py",T+"test_toolbelt_integrity.py","test_stageable_and_read_safe_relation_is_pinned"),
 ("R15-AGENT-066","py",T+"test_mcp_catalog_parity.py","test_run_custom_backtest_not_read_only_on_mcp"),
 ("R15-AGENT-067","py",T+"test_mcp_catalog_parity.py","test_mcp_projection_is_explicit_per_entry"),
 ("R15-CODE-AGENT-026","py",T+"test_mcp_catalog_parity.py","test_toolkind_has_no_unprojected_mcp_endpoint"),
 ("R15-CODE-PLATFORM-076","py",T+"test_agent_runtime.py","test_agent_system_prompts_within_byte_budget"),
 ("R15-CODE-FRONTEND-034","vt","src/store/proposed-changes.test.ts","a reworded Kept label still acks kept_previous"),
 ("R15-CODE-FRONTEND-035","vt","src/lib/host-actions.test.ts","write_note append with a trailing-whitespace addendum equals appendSymbolNote"),
 ("R15-RESEARCH-041","py",T+"test_research_iter.py","test_structured_only_sources_are_not_web_available"),
 ("R15-CODE-RESEARCH-006","py",T+"test_research_depth.py","test_panel_threshold_single_source"),
 ("R15-RESEARCH-035","py",T+"test_research_iter.py","test_over_cap_report_keeps_facts_established"),
 ("R15-RESEARCH-042","py",T+"test_research_fast.py","test_below_floor_marker"),
 ("R15-RESEARCH-040","vt","src/modules/chat/DepthControl.test.tsx","Tier B + ULTRA renders an estimate before dispatch"),
 ("R15-UI-093","vt","src/modules/chat/mentions.test.ts","R15-UI-093: a quoted candidate renders description '[NMS: 227.1 +0.8%]'"),
 ("R15-UI-078","vt","src/store/portfolios.test.ts","D:validateHolding rejects blank cost, qty>1e12, names the field for 1,000 (R15-UI-078)"),
 ("R15-CODE-PLATFORM-050","vt","src/modules/portfolio/metrics.test.ts","buildPortfolioSummary > rows carry the real holding id (R15-CODE-PLATFORM-050: no synthetic array-index id)"),
 ("R15-CODE-PLATFORM-051","vt","src/modules/portfolio/PortfolioPanel.test.tsx",None),
 ("R15-CODE-PLATFORM-052","vt","src/store/portfolios.test.ts",None),
 ("R15-UI-079","vt","src/lib/csv.test.ts","csv helpers > escapeCsvCell > R15-UI-079: prefixes a formula-trigger leading char so no text cell opens a live formula"),
 ("R15-AGENT-091","vt","src/modules/chat/context-provider.test.ts","P:captureTerminalState — portfolio holdings (FR-110/111, SC-024) > get_portfolio holdings carry a currency field on both the panel-published and store-fallback paths (R15-AGENT-091)"),
 ("R15-CODE-AGENT-017","py",T+"test_agents_store.py","test_unparseable_row_is_skipped_and_logged"),
 ("R15-CODE-AGENT-029","py",T+"test_agents_store.py","test_connect_is_idempotent"),
 ("R15-CODE-AGENT-029","py",T+"test_plugins.py","test_connect_is_idempotent"),
 ("R15-CODE-AGENT-029","py",T+"test_portfolio.py","test_connect_is_idempotent"),
 ("R15-CODE-AGENT-029","py",T+"test_schema_version.py",None),
 ("R15-CODE-AGENT-032","py",T+"test_runs_store.py","test_list_runs_is_bounded_and_prunes_old_terminal_rows"),
 ("R15-CODE-AGENT-032","vt","src/lib/delegate-runs.test.ts","skips a poll while one is in flight, and bounds the /runs read with a timeout"),
 ("R15-CODE-PLATFORM-055","rs","src-tauri/src/lib.rs","tests::write_atomic_text_and_bytes"),
 ("R15-CODE-PLATFORM-054","rs","src-tauri/src/lib.rs","tests::write_atomic_round_trip_leaves_no_tmp"),
 ("R15-CROSS-PLATFORM-007","py",T+"test_workspace.py","test_replace_retries_permission_error_then_succeeds"),
 ("R15-CODE-PLATFORM-056","rs","src-tauri/src/keychain.rs","keychain::tests::dev::migrate_with_erroring_reader_leaves_unmigrated_and_retries"),
 ("R15-CODE-PLATFORM-057","rs","src-tauri/src/keychain.rs","keychain::tests::dev::on_wait_called_before_sleep"),
 ("R15-CROSS-PLATFORM-011","vt","src/store/onboarding.test.ts","rejecting keychain keeps seen:true once markSeen ran (R15-CROSS-PLATFORM-011)"),
 ("R15-CROSS-PLATFORM-008","rs","src-tauri/src/lib.rs","tests::no_env_mutation_in_src"),
 ("R15-LIFECYCLE-037","rs","src-tauri/src/lib.rs","tests::clear_mcp_endpoint_file_removes_existing"),
 ("R15-CODE-PLATFORM-074","rs","src-tauri/src/lib.rs","tests::clear_mcp_endpoint_file_removes_existing"),
 ("R15-LIFECYCLE-038","rs","src-tauri/src/lib.rs","tests::plain_tcp_listener_is_not_healthy"),
 ("R15-RELEASE-009","rs","src-tauri/src/lib.rs","tests::smoke_bind_budget_matches_supervisor"),
 ("R15-UI-075","vt","scripts/audit-design-tokens.test.mjs","body font-feature-settings enables zero (matches tokens.css's slashed-zero claim)"),
 ("R15-CODE-PLATFORM-070","vt","scripts/audit-design-tokens.test.mjs","a mismatched fallback fails the audit"),
 ("R15-UI-076","vt","src/store/symbols.test.ts",None),
 ("R15-UI-076","vt","src/store/chart-drawings.test.ts",None),
 ("R15-CODE-PLATFORM-049","vt","src/store/marketplace.test.ts","P:marketplace store — install/enable/configure/remove (FR-050/US10/SC-013) > remove(vysted-news) deletes each granted secret; disable does not (R15-CODE-PLATFORM-049)"),
 ("R15-UI-089","vt","src/modules/marketplace/MarketplacePanel.test.tsx",None),
 ("R15-AGENT-087","vt","src/store/agent-mode.test.ts",None),
 ("R15-CODE-RESEARCH-007","py",T+"test_research_semantics.py","test_emitted_keys_subset_of_brief_ts_mirror"),
 ("R15-RESEARCH-036","py",T+"test_research_semantics.py","test_prompt_keys_cover_every_derived_metric"),
 ("R15-CODE-RESEARCH-011","py",T+"test_research_semantics.py","test_every_leg_returns_facts_and_conflicts"),
 ("R15-CODE-RESEARCH-008","py",T+"test_research_hosted_lanes.py","test_both_lanes_map_the_same_status_set_incl_402"),
 ("R15-CODE-PLATFORM-061","vt","scripts/sidecar-staleness.test.mjs","survives a source file deleted between readdir and stat (TOCTOU, R15-CODE-PLATFORM-061)"),
 ("R15-CODE-PLATFORM-062","vt","scripts/smoke-test-sidecars.test.mjs","D:_httpGetOk (R15-CODE-PLATFORM-062)"),
 ("R15-LIFECYCLE-039","vt","scripts/smoke-test-sidecars.test.mjs","D:_scopedOrphanPreflight (R15-LIFECYCLE-039)"),
 ("R15-RELEASE-008","vt","scripts/smoke-test-sidecars.test.mjs","D:_shouldProbeExchanges (R15-RELEASE-008)"),
 ("R15-CROSS-PLATFORM-010","vt","scripts/smoke-test-sidecars.test.mjs","D:ci-local's pip installs (R15-CROSS-PLATFORM-010)"),
 ("R15-RELEASE-011","vt","scripts/smoke-test-sidecars.test.mjs","D:coverage gate (R15-RELEASE-011)"),
 ("R15-CODE-PLATFORM-064","vt","scripts/smoke-test-sidecars.test.mjs","D:dead Phase-6 screenshot generators stay deleted (R15-CODE-PLATFORM-064)"),
 ("R15-CODE-AGENT-028","py",T+"test_agent_tools_lows.py","test_no_agent_tools_registry_v0_6_0_module"),
 ("R15-CODE-AGENT-027","py",T+"test_agent_tools_lows.py","test_reset_for_tests_restores_every_import_time_tool"),
 ("R15-CODE-AGENT-014","py",T+"test_agent_tools_lows.py","test_invoke_tool_wraps_provider_error_with_one_spelling"),
 ("R15-AGENT-068","py",T+"test_agent_tools_lows.py","test_earnings_upcoming_bad_days_returns_range_message"),
 ("R15-CODE-AGENT-015","py",T+"test_sec_tools.py","test_limit_is_clamped_both_ways"),
 ("R15-AGENT-069","py",T+"test_compare_symbols.py","test_one_raising_symbol_yields_one_error_row"),
 ("R15-AGENT-069","py",T+"test_market_overview.py","test_one_raising_quote_yields_one_error_row"),
 ("R15-DATA-101","py",T+"test_market_overview.py","test_global_region_carries_us_proxy_note"),
 ("R15-AGENT-072","py",T+"test_agents_router.py","test_agents_expose_effective_grant_separately_from_specialty_tools"),
 ("R15-LIFECYCLE-030","py",T+"test_fundamentals_warm.py","test_in_boot_seeds_exactly_once"),
 ("R15-LIFECYCLE-031","py",T+"test_fundamentals_warm.py","test_start_stop_clean_no_leaked_tasks"),
 ("R15-LIFECYCLE-032","py",T+"test_fundamentals_warm.py","test_one_upsert_failure_counts_the_others"),
 ("R15-CODE-DATA-020","py",T+"test_screener_router.py","test_internal_error_is_500_formula_error_is_400"),
 ("R15-DATA-107","py",T+"test_screener_india.py","test_india_symbol_meta_fields_by_name"),
 ("R15-DATA-108","py",T+"test_screener_india.py","test_sector_master_parsed_once"),
 ("R15-LEAD-029","py",T+"test_screener_india.py","test_nse_lookup_docstring_count_matches_india_all_length"),
 ("R15-CODE-DATA-007","py",T+"test_corporate_disclosures.py","test_lane_keyerror_degrades_to_partial_merge"),
 ("R15-CODE-DATA-007","py",T+"test_corporate_disclosures.py","test_shareholding_lane_keyerror_falls_through_to_next_lane"),
 ("R15-LEAD-017","py",T+"test_corporate_disclosures.py","test_duplicate_quarter_rows_collapse_to_one"),
 ("R15-CODE-DATA-008","py",T+"test_provider_registry.py","test_resolve_sync_keyerror_falls_through_to_next_candidate"),
 ("R15-CODE-DATA-008","py",T+"test_provider_registry.py","test_resolve_async_keyerror_falls_through_to_next_candidate"),
 ("R15-CODE-DATA-010","py",T+"test_data_cache.py","test_stale_get_evicts_row"),
 ("R15-CODE-PLATFORM-077","py",T+"test_data_cache.py","test_old_upgrade_backups_are_pruned_after_a_successful_backup"),
 ("R15-LEAD-020","py",T+"test_exchange_financials_negcache.py",None),
 ("R15-DATA-104","py",T+"test_earnings_provider.py","test_get_upcoming_caps_concurrent_calendar_fetches"),
 ("R15-DATA-104","py",T+"test_earnings_provider.py","test_get_upcoming_skips_fetch_when_yahoo_circuit_is_open"),
 ("R15-LIFECYCLE-033","py",T+"test_system_router.py","test_provider_health_mutations_404_without_rig_hooks_flag"),
 ("R15-LIFECYCLE-033","py",T+"test_system_router.py","test_provider_health_mutations_work_with_rig_hooks_flag"),
 ("R15-LIFECYCLE-034","py",T+"test_searxng_manager.py","test_setup_write_settings_oserror_reports_error_with_reason"),
 ("R15-CODE-AGENT-019","py",T+"test_llm_router.py","test_validate_transport_failure_is_humanized"),
 ("R15-CODE-AGENT-021","py",T+"test_llm_router.py","test_no_llm_route_echoes_the_key"),
 ("R15-CODE-AGENT-022","py",T+"test_mcp_server.py","test_status_protocol_version_matches_initialize_handshake"),
 ("R15-CODE-AGENT-023","py",T+"test_mcp_server.py","test_failing_catalog_tool_returns_is_error"),
 ("R15-CODE-AGENT-025","py",T+"test_mcp_client.py","test_call_tool_passes_structured_content_through"),
 ("R15-CODE-AGENT-024","py",T+"test_mcp_client.py","test_local_mcp_subprocess_resolves_and_decodes_once"),
 ("R15-CODE-DATA-013","py",T+"test_sec_filings_router.py","test_sections_route_is_gone"),
 ("R15-CODE-FRONTEND-026","vt","src/store/workflow.test.ts","append a, take, append b -> b still pending"),
 ("R15-CODE-FRONTEND-022","vt","src/components/CommandPalette.test.tsx","agent row selection uses agentSummary.id"),
 ("R15-UI-065","vt","src/lib/open-panel-literals.test.ts","panel-id literals (R15-UI-065) > every openPanel('literal') / opensPanel literal under src/ resolves to a registered panel"),
 ("R15-UI-081","vt","src/store/workspace.test.ts","disabled portfolio: openPanel returns false, no panel added"),
 ("R15-CODE-FRONTEND-036","vt","src/lib/layout-templates.test.ts","every ARRANGEABLE/PANEL/DEFAULT_PANELS {id, component} equals a registered PanelSpec"),
 ("R15-AGENT-078","vt","src/lib/layout-templates.test.ts","applyLayoutTemplate/applyCustomLayout apply without a rAF flush"),
 ("R15-CODE-FRONTEND-025","vt","src/components/PanelHost.test.tsx","fromJSON with a sub-minimum panel grows it"),
 ("R15-LIFECYCLE-029","vt","src/components/PanelHost.test.tsx","saved layout with a plugin panel restores intact when the plugin registers after bootstrap"),
 ("R15-CROSS-PLATFORM-009","vt","src/lib/source-guards.test.ts","no string or JSX text under src/ contains ⌘ outside src/store/keybindings.ts"),
 ("R15-DOCS-006","vt","src/lib/source-guards.test.ts","no 'static-export'/'SSR-safe' claim under src/ outside the shrinking allowlist"),
 ("R15-CODE-FRONTEND-029","vt","src/components/CommandPalette.test.tsx","custom agent added while open appears"),
 ("R15-LEAD-027","vt","src/store/command-palette.test.ts","no two empty-query rows share a panelId"),
 ("R15-CODE-FRONTEND-030","vt","src/store/settings.test.ts","R15-CODE-FRONTEND-030: fresh store, setActiveAgent(copilot), setAll({defaultAgentId: quant}) keeps copilot"),
 ("R15-CODE-FRONTEND-037","vt","src/lib/workspace.test.ts","R15-CODE-FRONTEND-037: empty watchlist round-trips to []; a blob without the key keeps defaults"),
 ("R15-LIFECYCLE-028","vt","src/lib/workspace.test.ts","R15-LIFECYCLE-028: pagehide with a pending autosave issues the POST immediately"),
 ("R15-UI-070","vt","src/modules/platform/WorkspaceDialog.test.tsx","exports a saved workspace to a .vysted-workspace file and imports it back under a chosen name"),
 ("R15-CODE-FRONTEND-028","vt","src/store/research-spaces.test.ts","R15-CODE-FRONTEND-028: an errored reply round-trips with its status; a pending one is not captured"),
 ("R15-CODE-FRONTEND-028","vt","src/lib/workspace.test.ts","R15-CODE-FRONTEND-028: agent spaces survive serialize -> deserialize"),
 ("R15-CODE-PLATFORM-039","vt","src/lib/search-headers.test.ts","includeKey:false omits the key and never reads the keychain, tier/models still ride (R15-CODE-PLATFORM-039)"),
 ("R15-DATA-109","vt","src/lib/sidecar-client.test.ts","openCryptoStream is not exported"),
 ("R15-LIFECYCLE-027","vt","src/lib/sidecar-client.test.ts","D:request timeouts"),
 ("R15-LIFECYCLE-027","vt","src/lib/plugin-bootstrap.test.ts","persistence.load is called exactly once per catalog plugin"),
 ("R15-CODE-PLATFORM-047","vt","src/lib/plugin-runtime.test.ts","disable during a pending healthCheck stays stopped, not reverted to active"),
 ("R15-CODE-PLATFORM-048","vt","src/lib/plugin-runtime.test.ts","P:'<0.9.0' is rejected as unsupported"),
 ("R15-CODE-PLATFORM-048","vt","src/lib/plugin-runtime.test.ts","a '<' required version is always false, on either side of it"),
 ("R15-CODE-PLATFORM-044","py",T+"test_llm_lows.py","test_stream_chat_abc_is_not_a_coroutine_function"),
 ("R15-CODE-AGENT-030","py",T+"test_llm_lows.py","test_validate_key_has_no_reraise_only_clause"),
 ("R15-CODE-AGENT-020","py",T+"test_llm_lows.py","test_get_provider_groq_gemini_honour_or_reject_base_url"),
 ("R15-AGENT-076","py",T+"test_llm_ollama.py","test_tools_construction_error_logs_and_emits_notice"),
 ("R15-RESEARCH-031","vt","src/modules/chat/streaming.test.ts","multi-line query research:begin fires beginRun with the full query"),
 ("R15-CODE-FRONTEND-021","vt","src/modules/chat/ChatSidebar.test.tsx","ContextBadge hidden with no bus events, shown with one panel event (asserted on kind) (R15-CODE-FRONTEND-021)"),
 ("R15-CODE-FRONTEND-032","vt","src/modules/chat/ChatSidebar.test.tsx","/clear rejects a pending write_note and acks it failed (R15-CODE-FRONTEND-032)"),
 ("R15-AGENT-075","py",T+"test_budget_guard.py","test_prices_with_served_model"),
 ("R15-CODE-PLATFORM-038","py",T+"test_run_manager.py","test_crashed_run_detail_is_humanized"),
 ("R15-LIFECYCLE-036","py",T+"test_symbol_resolver.py","test_garbled_master_degrades_to_no_match_not_500"),
 ("R15-CODE-DATA-017","py",T+"test_symbol_resolver.py","test_autocomplete_exact_ticker_carries_exact_band_and_binds"),
 ("R15-CODE-DATA-018","py",T+"test_symbol_resolver.py",None),
 ("R15-CODE-DATA-018","py",T+"test_resolver_rename.py",None),
 ("R15-CODE-DATA-009","py",T+"test_provider_health.py","test_is_rate_limit_union"),
 ("R15-LEAD-006","py",T+"test_growth_check.py",None),
 ("R15-LEAD-006","py",T+"test_earnings_quality.py",None),
 ("R15-CODE-DATA-022","py",T+"test_fundamentals_models.py","test_field_meta_status_rejects_unknown"),
 ("R15-DATA-103","py",T+"test_fundamentals_store.py","test_null_change_row_keeps_change_unset_and_row_currency"),
 ("R15-DATA-105","py",T+"test_history.py","test_freshness_label_failure_yields_unknown"),
 ("R15-UI-067","vt","src/components/DataBadges.test.tsx","dates EOD in the viewer's local calendar across IST midnight (R15-UI-067)"),
 ("R15-UI-094","py",T+"test_company_narrative.py","test_five_section_fixture_parses_all_fields"),
 ("R15-UI-074","vt","src/modules/research/brief-layout.test.tsx","caps heading, prose and list blocks at max-w-prose but lets a table use the panel width"),
 ("R15-CODE-FRONTEND-023","vt","src/modules/chart/ChartPanel.test.tsx","N crosshair moves on a lone chart cause 0 ChartPanel re-renders (R15-CODE-FRONTEND-023)"),
 ("R15-UI-064","vt","src/modules/chart/ChartPanel.test.tsx","a % comparison overlay gets sorted, de-duplicated points on a VISIBLE left scale (R15-UI-064)"),
 ("R15-CODE-PLATFORM-041","py",T+"test_quant_options.py","test_validate_domain_rejects_steps_2_and_low_paths"),
 ("R15-CODE-PLATFORM-042","py",T+"test_quant_greeks.py","test_compute_greeks_equals_price_european_bs"),
 ("R15-UI-063","vt","src/lib/date-defaults.test.ts",None),
 ("R15-UI-063","vt","src/modules/quant/OptionPricerPanel.test.tsx","D:OptionPricerPanel date defaults (R15-UI-063)"),
 ("R15-UI-063","vt","src/modules/quant/YieldCurvePanel.test.tsx","D:YieldCurvePanel date defaults (R15-UI-063)"),
 ("R15-UI-062","vt","src/modules/backtest/BacktestPanel.test.tsx","D:*date default"),
 ("R15-UI-077","py",T+"test_quant_router.py","test_duplicate_pillar_is_400"),
 ("R15-UI-077","vt","src/modules/quant/YieldCurvePanel.test.tsx","R15-UI-077: two instruments on the same pillar names the duplicate and blocks the POST"),
 ("R15-DATA-098","py",T+"test_quant_yield_curve.py","test_grid_distinct_and_within_max_tenor"),
 ("R15-CODE-PLATFORM-043","py",T+"test_macro_providers.py","test_provider_constants_are_macro_provider_values"),
 ("R15-DATA-099","py",T+"test_macro_providers.py","test_fred_sa_bw_map_to_other"),
 ("R15-CODE-PLATFORM-065","py",T+"test_workflow_router.py","test_dangling_edge_yields_one_run_error_frame"),
 ("R15-CODE-PLATFORM-075","py",T+"test_workflow_router.py","test_resume_from_is_rejected_not_silently_rerun"),
 ("R15-CODE-PLATFORM-066","py",T+"test_workflow_builtin_nodes.py","test_huge_pow_and_repeat_rejected_fast"),
 ("R15-CODE-PLATFORM-067","py",T+"test_workflow_builtin_nodes.py","test_zero_input_not_replaced_by_config_and_unknown_provider_errors"),
 ("R15-CODE-PLATFORM-068","py",T+"test_workflow_builtin_nodes.py","test_create_app_registers_every_builtin_node"),
 ("R15-CODE-PLATFORM-069","vt","src/modules/node-editor/node-registry.test.ts","plugin node absent from the server list is not runnable"),
 ("R15-CODE-DATA-011","py",T+"test_router_cached_helper.py","test_corrupt_cache_entry_refetches_for_all_rating_routes"),
 ("R15-CODE-DATA-012","py",T+"test_router_cached_helper.py","test_corrupt_cache_entry_refetches_for_all_rating_routes"),
 ("R15-CODE-DATA-021","py",T+"test_range_check.py",None),
 ("R15-DOCS-013","py",T+"test_range_check.py","test_yfinance_served_series_declines_to_witness"),
 ("R15-DATA-106","py",T+"test_india_sector_map.py","test_enrichment_writes_canonical_seven_keys"),
 ("R15-CODE-FRONTEND-024","vt","src/lib/dead-surface.test.ts","R15-CODE-FRONTEND-024: no live source references a deleted dead-code symbol > finds zero references to fuzzyRank/fuzzyScore/exportNoteMd under src/"),
 ("R15-CROSS-PLATFORM-006","vt","src/lib/safe-filename.test.ts","P:safeFilename > maps "),
 ("R15-DOCS-010","vt","src/modules/notes/NotesToolbar.test.tsx","NotesToolbar — R15-DOCS-010 > the active toolbar button carries the fill class"),
 ("R15-CODE-DATA-014","vt","src/modules/sec/SecFilingsPanel.test.tsx","R15-CODE-DATA-014: a filingsByIdentifier update after mount re-renders the row count"),
 ("R15-CODE-DATA-015","vt","src/modules/earnings/EarningsCalendarPanel.test.tsx","R15-CODE-DATA-015: skeleton and loaded colgroups share widths"),
 ("R15-CODE-DATA-016","vt","src/modules/analyst-ratings/format.test.ts","fmtDate > parses a YYYY-MM-DD date as a local calendar date, never UTC midnight"),
 ("R15-UI-066","vt","src/components/EmptyState.test.tsx","EmptyState > R15-UI-066: variant 'error' renders role=alert and a distinct icon"),
 ("R15-UI-069","vt","src/modules/screener/ScreenerPanel.test.tsx",None),
 ("R15-UI-072","vt","src/modules/chat/ModelControl.test.tsx","R15-UI-072: the trigger contains a chevron icon"),
 ("R15-LEAD-021","vt","src/components/StatusChrome.test.tsx","an error status with a reason renders the reason in the chip title"),
 ("R15-UI-080","vt","src/modules/research/BriefPanel.test.tsx","a vysted:// source renders a provenance chip, no external link, and no favicon lookup"),
 ("R15-CODE-RESEARCH-009","py",T+"test_ddg_backend.py","test_one_search_with_lite_fallback_takes_one_pacing_slot"),
 ("R15-RESEARCH-039","py",T+"test_ddg_backend.py","test_403_then_429_reports_rate_limited"),
 ("R15-CODE-RESEARCH-010","py",T+"test_brave_backend.py",None),
 ("R15-CODE-RESEARCH-010","py",T+"test_mojeek_backend.py",None),
 ("R15-CODE-RESEARCH-012","py",T+"test_research_relevance.py","test_junk_filter_host_match_delegates_to_finance"),
 ("R15-DATA-111","py",T+"test_keyless_backend.py","test_nonempty_page_zero_rows_counts_parser_drift_failure"),
 ("R15-DATA-111","py",T+"test_keyless_backend.py","test_canary_real_results_record_success"),
 ("R15-DATA-111","py",T+"test_keyless_backend.py","test_canary_engine_error_counts_a_failure_with_its_own_note"),
 # REMAINING.json (fixed_untested)
 ("R15-CODE-RESEARCH-005","py",T+"test_research_module_boundary.py","test_no_research_module_imports_a_private_name_across_modules"),
 ("R15-CODE-RESEARCH-005","py",T+"test_research_module_boundary.py","test_shared_round_helpers_are_public_deep_exports"),
 ("R15-CODE-AGENT-031","py",T+"test_runs_router.py","test_runs_rows_carry_only_snake_case_keys"),
 ("R15-CODE-AGENT-031","py",T+"test_runs_router.py",None),
 ("R15-CODE-AGENT-031","py",T+"test_run_manager.py","test_run_output_is_returned_untruncated_by_get_run"),
 ("R15-CODE-AGENT-031","vt","src/lib/delegate-runs.test.ts",None),
 ("R15-CODE-DATA-019","py",T+"test_screener.py","test_result_row_has_no_matched_criteria"),
 ("R15-LIFECYCLE-035","py",T+"test_searxng_manager.py","test_hand_fixed_container_supersedes_a_sticky_error"),
 ("R15-LIFECYCLE-035","py",T+"test_searxng_manager.py","test_error_stays_sticky_while_the_container_is_not_serving"),
 ("R15-LIFECYCLE-035","py",T+"test_searxng_manager.py","test_hot_path_reprobes_a_sticky_error_on_a_throttle"),
 ("R15-CODE-FRONTEND-027","vt","src/store/agents.test.ts","P:refreshCustom 404"),
 ("R15-CODE-FRONTEND-027","vt","src/lib/sidecar-client.test.ts",None),
 ("R15-CODE-FRONTEND-027","vt","src/store/workflow.test.ts",None),
 ("R15-CODE-FRONTEND-027","vt","src/modules/node-editor/schedule-control.test.tsx",None),
 ("R15-AGENT-077","py",T+"test_llm_openai.py","test_repair_round_keeps_configured_base_url"),
 ("R15-AGENT-077","py",T+"test_native_search.py","test_native_search_oneshot_keeps_the_callers_base_url"),
 ("R15-DATA-102","py",T+"test_b7_exchange_financials.py","test_filed_growth_states_mrq_yoy_and_never_overrides_an_annual_basis"),
 ("R15-DATA-102","py",T+"test_fundamentals.py","test_served_growth_states_its_mrq_yoy_basis"),
 ("R15-DATA-102","py",T+"test_fundamentals_store.py","test_row_to_pair_growth_without_a_recorded_basis_states_none"),
 ("R15-CODE-PLATFORM-078","vt","scripts/sidecar-specs.test.mjs",None),
 ("R15-CODE-FRONTEND-038","vt","src/lib/export-artifact.test.ts",None),
 ("R15-CODE-PLATFORM-080","rs","src-tauri/src/lib.rs","tests::data_dir_override_wins_when_set_to_a_non_blank_value"),
 ("R15-CODE-FRONTEND-033","vt","src/lib/host-actions.test.ts",None),
 ("R15-CROSS-PLATFORM-012","py",T+"test_cache_dir.py",None),
 ("R15-UI-082","py",T+"test_workspace.py","test_a_32_char_devanagari_name_saves"),
 ("R15-UI-082","py",T+"test_workspace.py","test_a_name_whose_encoded_bytes_exceed_the_cap_is_still_rejected"),
 ("R15-UI-073","vt","src/lib/warning-token-scope.test.ts",None),
 ("R15-UI-071","vt","src/components/SettingsPanel.test.tsx",None),
 ("R15-UI-068","vt","src/components/DataTable.test.tsx",None),
 ("R15-LEAD-036","py",T+"test_agent_runtime.py","test_a_fence_opened_before_a_tool_call_leaves_no_marker_when_replaced"),
 ("R15-LEAD-036","py",T+"test_agent_runtime.py","test_a_streamed_fence_is_closed_before_the_next_rounds_note"),
 ("R15-LEAD-036","py",T+"test_agent_runtime.py","test_a_fence_continued_on_an_ok_result_streams_as_written"),
]
UNTESTABLE = {
 "R15-DOCS-007":"n/a (docs-only)","R15-DOCS-009":"n/a (docs-only)","R15-CODE-PLATFORM-060":"n/a (docs-only)","R15-RELEASE-010":"n/a (docs-only)",
 "R15-DOCS-014":"n/a (docs-only)","R15-DOCS-019":"n/a (docs-only)","R15-DOCS-020":"n/a (docs-only)","R15-DOCS-021":"n/a (docs-only)",
 "R15-DOCS-022":"n/a (docs-only)","R15-DOCS-023":"n/a (docs-only)","R15-DOCS-012":"none, fix_shape calls for no pin",
 "R15-CODE-PLATFORM-040":"n/a (deletion, grep only)","R15-CODE-PLATFORM-058":"'cargo test --lib (22/22)', no named test (chain cargo test 31 passed)",
 "R15-CODE-PLATFORM-059":"clippy lint flag, no named test (chain clippy -D warnings green)","R15-DOCS-025":"doc-only, none named","R15-CODE-PLATFORM-079":"config-only, none named",
}
