CREATE TABLE fundamentals (
    symbol TEXT PRIMARY KEY,
    name TEXT,
    exchange TEXT,
    isin TEXT,
    scrip_code TEXT,
    bse_group TEXT,
    sector TEXT,
    industry TEXT,
    sector_source TEXT,
    currency TEXT,
    market_cap REAL,
    pe_ratio REAL,
    forward_pe REAL,
    peg_ratio REAL,
    price_to_book REAL,
    price_to_sales REAL,
    ev_to_ebitda REAL,
    book_value REAL,
    dividend_yield REAL,
    eps REAL,
    beta REAL,
    roe REAL,
    roa REAL,
    gross_margin REAL,
    operating_margin REAL,
    profit_margin REAL,
    debt_to_equity REAL,
    current_ratio REAL,
    quick_ratio REAL,
    revenue_growth REAL,
    earnings_growth REAL,
    fifty_two_week_high REAL,
    fifty_two_week_low REAL,
    fifty_two_week_change REAL,
    held_percent_insiders REAL,
    held_percent_institutions REAL,
    shares_outstanding REAL,
    quote_price REAL,
    quote_change REAL,
    quote_change_percent REAL,
    quote_volume REAL,
    quote_currency TEXT,
    quote_market_state TEXT,
    quote_timestamp TEXT,
    quote_updated_at REAL,
    v7_updated_at REAL,
    info_updated_at REAL,
    info_failed_at REAL,
    seed_updated_at REAL,
    eod_updated_at REAL,
    provider TEXT,
    growth_basis TEXT
);
CREATE INDEX idx_fundamentals_sector ON fundamentals(sector);
CREATE INDEX idx_fundamentals_mcap ON fundamentals(market_cap DESC);
CREATE INDEX idx_fundamentals_info_at ON fundamentals(info_updated_at);
