"""Bundled sp500.json universe pack tests (R15-LEAD-013).

The pack is a point-in-time membership snapshot regenerated by
``services.screener_universes.regenerate_sp500`` — these tests pin its shape
and catch it going stale, not the regeneration script itself (that's a
network-hitting maintenance tool, not something CI should run per-commit).
"""

from __future__ import annotations

import json
from datetime import UTC, date, datetime
from importlib import resources

STALENESS_LIMIT_DAYS = 180

# The batch-5 verification note (docs/redesign/verification/r15/stage-c/
# batch-5/VERDICTS.md): names the old pack carried that the screener could
# not resolve (acquired/merged out of the index).
_KNOWN_STALE_NAMES = frozenset(
    {
        "MMC",
        "FI",
        "ANSS",
        "CTLT",
        "DAY",
        "DFS",
        "HES",
        "HOLX",
        "IPG",
        "JNPR",
        "K",
        "MRO",
        "WBA",
        "CTRA",
    }
)


def _load_pack() -> dict:
    with (
        resources.files("services.screener_universes")
        .joinpath("sp500.json")
        .open("r", encoding="utf-8")
    ) as fp:
        return json.load(fp)


def test_pack_shape_is_unchanged() -> None:
    pack = _load_pack()
    assert set(pack.keys()) == {"id", "label", "asset_class", "snapshot_date", "source", "symbols"}
    assert pack["id"] == "sp500"
    assert pack["asset_class"] == "equity"
    assert isinstance(pack["symbols"], list)
    assert len(set(pack["symbols"])) == len(pack["symbols"])  # no duplicates


def test_known_current_constituents_are_present() -> None:
    symbols = set(_load_pack()["symbols"])
    assert {"BXP", "NVR", "UDR"} <= symbols


def test_known_stale_names_are_absent() -> None:
    symbols = set(_load_pack()["symbols"])
    assert not (symbols & _KNOWN_STALE_NAMES)


def test_snapshot_is_not_stale() -> None:
    pack = _load_pack()
    snapshot_date = date.fromisoformat(pack["snapshot_date"])
    age_days = (datetime.now(UTC).date() - snapshot_date).days
    assert age_days <= STALENESS_LIMIT_DAYS, (
        f"sp500.json snapshot_date is {age_days} days old (limit "
        f"{STALENESS_LIMIT_DAYS}) — re-run "
        "services.screener_universes.regenerate_sp500"
    )
